/**
 * @generated
 * @file Footer (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://willwong.design.webflow.com | Source site in Webflow}
 */
"use client";

import Block from "../webflow_modules/Basic/components/Block";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";
import Link from "../webflow_modules/Basic/components/Link";

/**
 * Props for {@link Footer}
 */
export type FooterProps = {};

/**
 * Footer
 *
 * @see {@link https://willwong.design.webflow.com | Source site in Webflow}
 */
export function Footer({}: FooterProps) {
  return (
    <Block className={"footer"} id={"Footer"} tag={"footer"}>
      <Block className={"flex-expand"} tag={"div"} />
      <Link
        aria-controls={"TestPanel"}
        block={"inline"}
        button={false}
        className={"footer__trigger"}
        data-desktop={"inactive"}
        data-trigger={"test"}
        id={"TestTrigger"}
        options={{
          href: "#",
        }}
      >
        <HtmlEmbed
          className={"icon icon--footer"}
          content={
            '<svg width="100%" height="100%" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 511.991"><path d="M203.7 480.9h0l-37.8 26.7c-7.3 5.2-16.9 5.8-24.9 1.7S128 497 128 488v-72H96c-53 0-96-43-96-96V96C0 43 43 0 96 0h320c53 0 96 43 96 96v224c0 53-43 96-96 96H295.6l-91.9 64.9zM268 376.8c8.1-5.7 17.8-8.8 27.7-8.8H416c26.5 0 48-21.5 48-48V96c0-26.5-21.5-48-48-48H96c-26.5 0-48 21.5-48 48v224c0 26.5 21.5 48 48 48h56a23.96 23.96 0 0 1 22.6 15.9c.9 2.5 1.4 5.2 1.4 8.1v49.7l91.9-64.9h.1zM287 127c9.4-9.4 24.6-9.4 33.9 0l64 64c9.4 9.4 9.4 24.6 0 33.9l-64 64c-9.4 9.4-24.6 9.4-33.9 0s-9.4-24.6 0-33.9l47-47-47-47c-9.4-9.4-9.4-24.6 0-33.9v-.1zm-62 34l-47 47 47 47c9.4 9.4 9.4 24.6 0 33.9s-24.6 9.4-33.9 0l-64-64c-9.4-9.4-9.4-24.6 0-33.9l64-64c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9v.1z"/></svg>'
          }
        />
      </Link>
      <Link
        aria-controls={"ChatPanel"}
        block={"inline"}
        button={false}
        className={"footer__trigger"}
        data-desktop={"active"}
        data-trigger={"chat"}
        id={"ChatTrigger"}
        options={{
          href: "#",
        }}
      >
        <HtmlEmbed
          className={"icon icon--footer"}
          content={
            '<svg width="100%" height="100%" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 511.991"><path d="M203.7 480.9h0l-37.8 26.7c-7.3 5.2-16.9 5.8-24.9 1.7S128 497 128 488v-72H96c-53 0-96-43-96-96V96C0 43 43 0 96 0h320c53 0 96 43 96 96v224c0 53-43 96-96 96H295.6l-91.9 64.9zM268 376.8c8.1-5.7 17.8-8.8 27.7-8.8H416c26.5 0 48-21.5 48-48V96c0-26.5-21.5-48-48-48H96c-26.5 0-48 21.5-48 48v224c0 26.5 21.5 48 48 48h56a23.96 23.96 0 0 1 22.6 15.9c.9 2.5 1.4 5.2 1.4 8.1v49.7l91.9-64.9h.1zM287 127c9.4-9.4 24.6-9.4 33.9 0l64 64c9.4 9.4 9.4 24.6 0 33.9l-64 64c-9.4 9.4-24.6 9.4-33.9 0s-9.4-24.6 0-33.9l47-47-47-47c-9.4-9.4-9.4-24.6 0-33.9v-.1zm-62 34l-47 47 47 47c9.4 9.4 9.4 24.6 0 33.9s-24.6 9.4-33.9 0l-64-64c-9.4-9.4-9.4-24.6 0-33.9l64-64c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9v.1z"/></svg>'
          }
        />
      </Link>
    </Block>
  );
}
