/**
 * @generated
 * @file Main (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://willwong.design.webflow.com | Source site in Webflow}
 */
"use client";

import Block from "../webflow_modules/Basic/components/Block";

/**
 * Props for {@link Main}
 */
export type MainProps = {
  slot?: React.ReactNode;
};

/**
 * Main
 *
 * @see {@link https://willwong.design.webflow.com | Source site in Webflow}
 */
export function Main({ slot }: MainProps) {
  return (
    <Block className={"canvas"} id={"Main"} tag={"main"}>
      {slot}
    </Block>
  );
}
