/**
 * @generated
 * @file Shell (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://willwong.design.webflow.com | Source site in Webflow}
 */
"use client";

import Block from "../webflow_modules/Basic/components/Block";
import { Chat } from "../panels/Chat";
import { Footer } from "./Footer";
import { Header } from "./Header";
import { Test } from "../panels/Test";

/**
 * Props for {@link Shell}
 */
export type ShellProps = {
  slot?: React.ReactNode;
};

/**
 * Shell
 *
 * @see {@link https://willwong.design.webflow.com | Source site in Webflow}
 */
export function Shell({ slot }: ShellProps) {
  return (
    <Block className={"shell"} tag={"div"}>
      <Header />
      <Block className={"stage"} tag={"div"}>
        {slot}
        <Test />
        <Chat />
      </Block>
      <Footer />
    </Block>
  );
}
