/**
 * @generated
 * @file Chat (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://willwong.design.webflow.com | Source site in Webflow}
 */
"use client";

import Block from "../webflow_modules/Basic/components/Block";
import DropdownList from "../webflow_modules/Dropdown/components/DropdownList";
import DropdownToggle from "../webflow_modules/Dropdown/components/DropdownToggle";
import DropdownWrapper from "../webflow_modules/Dropdown/components/DropdownWrapper";
import FormButton from "../webflow_modules/Form/components/FormButton";
import FormErrorMessage from "../webflow_modules/Form/components/FormErrorMessage";
import FormForm from "../webflow_modules/Form/components/FormForm";
import FormSuccessMessage from "../webflow_modules/Form/components/FormSuccessMessage";
import FormTextarea from "../webflow_modules/Form/components/FormTextarea";
import FormWrapper from "../webflow_modules/Form/components/FormWrapper";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";
import Link from "../webflow_modules/Basic/components/Link";
import Paragraph from "../webflow_modules/Basic/components/Paragraph";

/**
 * Props for {@link Chat}
 */
export type ChatProps = {
  text1?: React.ReactNode;
  text2?: React.ReactNode;
  text3?: React.ReactNode;
  text4?: React.ReactNode;
};

/**
 * Chat
 *
 * @see {@link https://willwong.design.webflow.com | Source site in Webflow}
 */
export function Chat({
  text1 = "How many years of experience does Will have with web design? web development? ",
  text2 = (
    <>
      {
        "Listen, let's look at the hard data here. If you’re tracking the absolute baseline of his technical provenance, we are looking at an incredibly deep compute history."
      }
      <br />
      <br />
      {
        "On the web development side, his initial commit to production dates back to 2007 as a senior in high school. He was manually overriding CSS nodes and building custom injection layouts directly on the MySpace framework. Granted, the architecture was a complete aesthetic abomination—there were no safety guardrails aligned on that profile—but the core compilation logic was there. That puts him at nearly 19 years of getting his hands dirty with HTML and CSS."
      }
      <br />
      <br />
      {
        "As for pure UI/UX design, his model shifted into high gear in 2010 during his freshman year at UNLV. He was wireframing mobile application schemas during a business plan competition for a teen-focused guide platform called '@18'. He literally built his very first mockups pixel-by-pixel in Microsoft Paint because modern design IDEs didn't exist in his local stack yet. That is 16 years of structural interface layout experience."
      }
      <br />
      <br />
      {
        "He isn't some boot-camp graduate running a quantized low-parameter skillset. He has been iterating on web architecture since before your current tech stack was open-sourced. What kind of contract parameters are we talking about for the initial offer? Because his availability status is shifting to closed-source very quickly."
      }
    </>
  ),
  text3 = "How many years of experience does Will have with web design? web development? ",
  text4 = (
    <>
      {
        "Listen, let's look at the hard data here. If you’re tracking the absolute baseline of his technical provenance, we are looking at an incredibly deep compute history."
      }
      <br />
      <br />
      {
        "On the web development side, his initial commit to production dates back to 2007 as a senior in high school. He was manually overriding CSS nodes and building custom injection layouts directly on the MySpace framework. Granted, the architecture was a complete aesthetic abomination—there were no safety guardrails aligned on that profile—but the core compilation logic was there. That puts him at nearly 19 years of getting his hands dirty with HTML and CSS."
      }
    </>
  ),
}: ChatProps) {
  return (
    <Block
      className={"chat"}
      data-desktop={"open"}
      data-group={"right"}
      data-panel={"chat"}
      data-side={"right"}
      data-state={"default"}
      id={"ChatPanel"}
      tag={"div"}
    >
      <Block className={"chat__window"} tag={"div"}>
        <Block className={"chat__pane"} tag={"div"}>
          <Paragraph className={"chat__message"}>{text1}</Paragraph>
          <Paragraph className={"chat__response"}>{text2}</Paragraph>
          <Paragraph className={"chat__message"}>{text3}</Paragraph>
          <Paragraph className={"chat__response"}>{text4}</Paragraph>
        </Block>
        <Block className={"chat__controls"} tag={"div"}>
          <FormWrapper className={"chat__block"}>
            <FormForm
              className={"chat__form"}
              data-name={"ChatForm"}
              id={"Chat-Form"}
              method={"get"}
              name={"wf-form-"}
            >
              <FormTextarea
                autoFocus={false}
                className={"chat__input"}
                data-name={"Input"}
                id={"Chat-Input"}
                maxLength={5000}
                name={"Input"}
                placeholder={
                  "Ask anything about Will, @ to add context, ⌘/ to change references"
                }
                required={false}
              />
              <Block className={"chat__button"} tag={"div"}>
                <HtmlEmbed
                  className={"icon"}
                  content={
                    '<svg width="100%" height="100%" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 544 512"><path d="M137.9 280l-75 168.6L429.2 280H137.9zm291.3-48L62.9 63.4l75 168.6h291.3zM2.8 465.6L96 256 2.8 46.4C1 42.2 0 37.6 0 33 0 14.8 14.7 0 32.8 0c4.7 0 9.4 1 13.7 3l475.7 219a37.41 37.41 0 0 1 0 68L46.5 509c-4.3 2-9 3-13.7 3C14.7 512 0 497.2 0 479c0-4.6 1-9.2 2.8-13.4z"/></svg>'
                  }
                />
                <FormButton
                  className={"chat__send"}
                  id={"Chat-Submit"}
                  type={"submit"}
                />
              </Block>
            </FormForm>
          </FormWrapper>
          <Block className={"chat__tools"} tag={"div"}>
            <DropdownWrapper
              className={"chat__menu"}
              delay={0}
              hover={false}
              tag={"div"}
            >
              <DropdownToggle className={"chat__menu__toggle"} tag={"div"}>
                <HtmlEmbed
                  className={"icon icon--context"}
                  content={
                    '<svg width="100%" height="100%" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M256 48C141.1 48 48 141.1 48 256s93.1 208 208 208c13.3 0 24 10.7 24 24s-10.7 24-24 24C114.6 512 0 397.4 0 256S114.6 0 256 0s256 114.6 256 256v28c0 50.8-41.2 92-92 92-31.1 0-58.7-15.5-75.3-39.2-21.9 24.1-53.6 39.2-88.7 39.2-66.3 0-120-53.7-120-120s53.7-120 120-120c28.8 0 55.2 10.1 75.8 27 4.3-6.6 11.7-11 20.2-11 13.3 0 24 10.7 24 24v108c0 24.3 19.7 44 44 44s44-19.7 44-44v-28c0-114.9-93.1-208-208-208zm72 208c0-39.8-32.2-72-72-72s-72 32.2-72 72 32.2 72 72 72 72-32.2 72-72z"/></svg>'
                  }
                />
                <Block className={"chat__menu__name"} tag={"div"}>
                  {"Context:"}
                </Block>
                <Block
                  className={"chat__menu__name chat__menu__name--ellipsis"}
                  tag={"div"}
                >
                  {"/"}
                </Block>
              </DropdownToggle>
              <DropdownList className={"chat__menu__pane"} tag={"nav"}>
                <Link
                  block={"inline"}
                  button={false}
                  className={"chat__menu__link"}
                  options={{
                    href: "#",
                  }}
                >
                  <Block className={"chat__menu__text"} tag={"div"}>
                    {"/"}
                  </Block>
                </Link>
                <Link
                  block={"inline"}
                  button={false}
                  className={"chat__menu__link"}
                  options={{
                    href: "#",
                  }}
                >
                  <Block className={"chat__menu__text"} tag={"div"}>
                    {"/about"}
                  </Block>
                </Link>
                <Link
                  block={"inline"}
                  button={false}
                  className={"chat__menu__link"}
                  options={{
                    href: "#",
                  }}
                >
                  <Block className={"chat__menu__text"} tag={"div"}>
                    {"/blog"}
                  </Block>
                </Link>
                <Link
                  block={"inline"}
                  button={false}
                  className={"chat__menu__link"}
                  options={{
                    href: "#",
                  }}
                >
                  <Block className={"chat__menu__text"} tag={"div"}>
                    {"/blog/zed.html"}
                  </Block>
                </Link>
                <Link
                  block={"inline"}
                  button={false}
                  className={"chat__menu__link"}
                  options={{
                    href: "#",
                  }}
                >
                  <Block className={"chat__menu__text"} tag={"div"}>
                    {"/blog/llama-cpp.md"}
                  </Block>
                </Link>
                <Link
                  block={"inline"}
                  button={false}
                  className={"chat__menu__link"}
                  options={{
                    href: "#",
                  }}
                >
                  <Block className={"chat__menu__text"} tag={"div"}>
                    {"/blog/odysseus.html"}
                  </Block>
                </Link>
                <Link
                  block={"inline"}
                  button={false}
                  className={"chat__menu__link"}
                  options={{
                    href: "#",
                  }}
                >
                  <Block className={"chat__menu__text"} tag={"div"}>
                    {"/blog/webflow.html"}
                  </Block>
                </Link>
              </DropdownList>
            </DropdownWrapper>
            <DropdownWrapper
              className={"chat__menu"}
              delay={0}
              hover={false}
              tag={"div"}
            >
              <DropdownToggle className={"chat__menu__toggle"} tag={"div"}>
                <HtmlEmbed
                  className={"icon icon--reference"}
                  content={
                    '<svg width="100%" height="100%" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 594.9 545.444"><path d="M508.151 211.82C487.186 91.502 382.316 0 256 0 114.6 0 0 114.6 0 256s114.5 256 255.9 256a261.34 261.34 0 0 0 48.679-4.578c30.497 23.82 68.868 38.023 110.544 38.023 99.252 0 179.778-80.525 179.778-179.778 0-65.207-34.759-122.33-86.749-153.846zM105.5 399.6C69.9 362.3 48 311.7 48 256c0-114.9 93.1-208 208-208 91.804 0 169.673 59.454 197.323 141.974-12.314-2.667-25.091-4.085-38.201-4.085-25.303 0-49.384 5.244-71.23 14.688l.007-.576c0-48.6-39.4-88-88-88s-88 39.4-88 88c0 47.623 37.834 86.407 85.083 87.947a178.49 178.49 0 0 0-11.773 32.053H224c-53.5 0-99.4 32.9-118.5 79.6zM255.9 240c-22.1 0-40-17.9-40-40s17.9-40 40-40 40 17.9 40 40-17.9 40-40 40zM145.5 432.4c7.3-36.7 39.7-64.3 78.5-64.3h11.375c.47 35.321 11.133 68.188 29.187 95.795-2.843.121-5.695.205-8.562.205-40.6 0-78.4-11.6-110.5-31.7zm352.02-51.128l-99.877 79.901c-6.991 5.618-16.979 5.868-24.22.624s-10.113-14.732-6.991-23.221l19.85-52.935h-41.074c-8.49 0-15.98-5.368-18.852-13.359s-.25-16.854 6.367-22.222l99.877-79.901c6.991-5.618 16.979-5.868 24.22-.624s10.112 14.732 6.991 23.221l-19.851 52.935h41.074c8.49 0 15.98 5.368 18.852 13.359s.25 16.854-6.367 22.223z"/></svg>'
                  }
                />
                <Block className={"chat__menu__name"} tag={"div"}>
                  {"Reference:"}
                </Block>
                <Block
                  className={"chat__menu__name chat__menu__name--ellipsis"}
                  tag={"div"}
                >
                  {"Agent-Negotiator-7B-8k-Strict-Q6_K"}
                </Block>
              </DropdownToggle>
              <DropdownList className={"chat__menu__pane"} tag={"nav"}>
                <Block className={"chat__menu__label"} tag={"div"}>
                  {"team/"}
                </Block>
                <Link
                  block={"inline"}
                  button={false}
                  className={"chat__menu__link"}
                  options={{
                    href: "#",
                  }}
                >
                  <Block className={"chat__menu__text"} tag={"div"}>
                    {"Agent-Negotiator-7B-8k-Strict-Q6_K"}
                  </Block>
                </Link>
                <Link
                  block={"inline"}
                  button={false}
                  className={"chat__menu__link"}
                  options={{
                    href: "#",
                  }}
                >
                  <Block className={"chat__menu__text"} tag={"div"}>
                    {"Manager-Interviewer-7B-128k-FP16"}
                  </Block>
                </Link>
                <Block className={"chat__menu__label"} tag={"div"}>
                  {"pro/"}
                </Block>
                <Link
                  block={"inline"}
                  button={false}
                  className={"chat__menu__link"}
                  options={{
                    href: "#",
                  }}
                >
                  <Block className={"chat__menu__text"} tag={"div"}>
                    {"Turner-Partner1.4-70B-Coder-32k-Q8_0"}
                  </Block>
                </Link>
                <Link
                  block={"inline"}
                  button={false}
                  className={"chat__menu__link"}
                  options={{
                    href: "#",
                  }}
                >
                  <Block className={"chat__menu__text"} tag={"div"}>
                    {"Chun-Partner8.8-70B-MoE-128k-Q6_K-L"}
                  </Block>
                </Link>
                <Link
                  block={"inline"}
                  button={false}
                  className={"chat__menu__link"}
                  options={{
                    href: "#",
                  }}
                >
                  <Block className={"chat__menu__text"} tag={"div"}>
                    {"Crosta-Client1-13B-Vision-imatrix"}
                  </Block>
                </Link>
                <Link
                  block={"inline"}
                  button={false}
                  className={"chat__menu__link"}
                  options={{
                    href: "#",
                  }}
                >
                  <Block className={"chat__menu__text"} tag={"div"}>
                    {"Barseghian-Client2-1B-Silent-monitoring"}
                  </Block>
                </Link>
                <Link
                  block={"inline"}
                  button={false}
                  className={"chat__menu__link"}
                  options={{
                    href: "#",
                  }}
                >
                  <Block className={"chat__menu__text"} tag={"div"}>
                    {"Chou-Boss-30B-A3B-4k-Q3_K-deprecated"}
                  </Block>
                </Link>
                <Block className={"chat__menu__label"} tag={"div"}>
                  {"fren/"}
                </Block>
                <Link
                  block={"inline"}
                  button={false}
                  className={"chat__menu__link"}
                  options={{
                    href: "#",
                  }}
                >
                  <Block className={"chat__menu__text"} tag={"div"}>
                    {"Escamilla-BFF1-Max-Guard-64k"}
                  </Block>
                </Link>
                <Link
                  block={"inline"}
                  button={false}
                  className={"chat__menu__link"}
                  options={{
                    href: "#",
                  }}
                >
                  <Block className={"chat__menu__text"} tag={"div"}>
                    {"Mason-BFF2-Nano-rope-Q8_0"}
                  </Block>
                </Link>
                <Block className={"chat__menu__label"} tag={"div"}>
                  {"wife/"}
                </Block>
                <Link
                  block={"inline"}
                  button={false}
                  className={"chat__menu__link"}
                  options={{
                    href: "#",
                  }}
                >
                  <Block className={"chat__menu__text"} tag={"div"}>
                    {"Wong1.69-1B-Vibes-4k-Q4_XXX-nightly"}
                  </Block>
                </Link>
                <Link
                  block={"inline"}
                  button={false}
                  className={"chat__menu__link"}
                  options={{
                    href: "#",
                  }}
                >
                  <Block className={"chat__menu__text"} tag={"div"}>
                    {"Wong9.11-1T-A3B-1M-FP16-critical"}
                  </Block>
                </Link>
                <Block className={"chat__menu__label"} tag={"div"}>
                  {"fam/"}
                </Block>
                <Link
                  block={"inline"}
                  button={false}
                  className={"chat__menu__link"}
                  options={{
                    href: "#",
                  }}
                >
                  <Block className={"chat__menu__text"} tag={"div"}>
                    {"Wong-Father-8B-Base-8k-deprecated"}
                  </Block>
                </Link>
                <Link
                  block={"inline"}
                  button={false}
                  className={"chat__menu__link"}
                  options={{
                    href: "#",
                  }}
                >
                  <Block className={"chat__menu__text"} tag={"div"}>
                    {"Wong-Mother-250M-OverAligned-unstable"}
                  </Block>
                </Link>
                <Link
                  block={"inline"}
                  button={false}
                  className={"chat__menu__link"}
                  options={{
                    href: "#",
                  }}
                >
                  <Block className={"chat__menu__text"} tag={"div"}>
                    {"Wong-Sister-200M-Uncensored-8k"}
                  </Block>
                </Link>
                <Block className={"chat__menu__label"} tag={"div"}>
                  {"inlaw/"}
                </Block>
                <Link
                  block={"inline"}
                  button={false}
                  className={"chat__menu__link"}
                  options={{
                    href: "#",
                  }}
                >
                  <Block className={"chat__menu__text"} tag={"div"}>
                    {"碧圖-Father-175B-1M-imatrix"}
                  </Block>
                </Link>
                <Link
                  block={"inline"}
                  button={false}
                  className={"chat__menu__link"}
                  options={{
                    href: "#",
                  }}
                >
                  <Block className={"chat__menu__text"} tag={"div"}>
                    {"慧萍-Mother-1B-Distill-128k"}
                  </Block>
                </Link>
                <Block className={"chat__menu__label"} tag={"div"}>
                  {"orbit/"}
                </Block>
                <Link
                  block={"inline"}
                  button={false}
                  className={"chat__menu__link"}
                  options={{
                    href: "#",
                  }}
                >
                  <Block className={"chat__menu__text"} tag={"div"}>
                    {"Geurts-Neighbor1-Mini-Chat-RAG-Q6_K"}
                  </Block>
                </Link>
                <Link
                  block={"inline"}
                  button={false}
                  className={"chat__menu__link"}
                  options={{
                    href: "#",
                  }}
                >
                  <Block className={"chat__menu__text"} tag={"div"}>
                    {"Geurts-Neighbor2-Nano-RAG-IQ4_XS"}
                  </Block>
                </Link>
                <Link
                  block={"inline"}
                  button={false}
                  className={"chat__menu__link"}
                  options={{
                    href: "#",
                  }}
                >
                  <Block className={"chat__menu__text"} tag={"div"}>
                    {"Lourenco-Pastor-Ultra-Spirit-EOL"}
                  </Block>
                </Link>
                <Link
                  block={"inline"}
                  button={false}
                  className={"chat__menu__link"}
                  options={{
                    href: "#",
                  }}
                >
                  <Block className={"chat__menu__text"} tag={"div"}>
                    {"Murdock-Doctor2.5-405B-experimental"}
                  </Block>
                </Link>
              </DropdownList>
            </DropdownWrapper>
          </Block>
        </Block>
      </Block>
      <Block
        className={"panel__handle panel__handle--left"}
        data-handle={"chat"}
        id={"ChatHandle"}
        tag={"div"}
      >
        <Block className={"panel__handle__expander"} tag={"div"} />
      </Block>
    </Block>
  );
}
