/**
 * @generated
 * @file Nav (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://willwong.design.webflow.com | Source site in Webflow}
 */
"use client";

import Block from "../webflow_modules/Basic/components/Block";

/**
 * Props for {@link Nav}
 */
export type NavProps = {
  slot?: React.ReactNode;
};

/**
 * Nav
 *
 * @see {@link https://willwong.design.webflow.com | Source site in Webflow}
 */
export function Nav({ slot }: NavProps) {
  return (
    <Block
      className={"nav"}
      data-desktop={"open"}
      data-group={"left"}
      data-panel={"nav"}
      data-side={"left"}
      data-state={"default"}
      id={"NavPanel"}
      tag={"nav"}
    >
      {slot}
      <Block
        className={"panel__handle"}
        data-handle={"nav"}
        id={"NavHandle"}
        tag={"div"}
      />
    </Block>
  );
}
