/**
 * @generated
 * @file Test (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://willwong.design.webflow.com | Source site in Webflow}
 */
"use client";

import Block from "../webflow_modules/Basic/components/Block";

/**
 * Props for {@link Test}
 */
export type TestProps = {};

/**
 * Test
 *
 * @see {@link https://willwong.design.webflow.com | Source site in Webflow}
 */
export function Test({}: TestProps) {
  return (
    <Block
      className={"test"}
      data-desktop={"closed"}
      data-group={"right"}
      data-panel={"test"}
      data-state={"default"}
      id={"TestPanel"}
      tag={"div"}
    />
  );
}
