/**
 * @generated
 * @file Language (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://willwong.design.webflow.com | Source site in Webflow}
 */
"use client";

import Block from "../webflow_modules/Basic/components/Block";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";

/**
 * Props for {@link Language}
 */
export type LanguageProps = {
  fill?: Record<string, unknown>;
  icon?: Record<string, unknown>;
  label?: React.ReactNode;
  value?: React.ReactNode;
};

/**
 * Language
 *
 * @see {@link https://willwong.design.webflow.com | Source site in Webflow}
 */
export function Language({
  fill = {},
  icon = {},
  label = "JSON",
  value = "55.5%",
}: LanguageProps) {
  return (
    <Block className={"stat"} tag={"div"}>
      <HtmlEmbed
        className={"icon icon--stat"}
        content={
          '<svg width="100%" height="100%" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576.05 512.11"><path d="M360.77 1.25c-17-4.9-34.7 5-39.6 22l-128 448c-4.9 17 5 34.7 22 39.6s34.7-5 39.6-22l128-448c4.9-17-5-34.7-22-39.6zm64.6 136.1c-12.5 12.5-12.5 32.8 0 45.3l73.4 73.4-73.4 73.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0l96-96c12.5-12.5 12.5-32.8 0-45.3l-96-96c-12.5-12.5-32.8-12.5-45.3 0v-.1zm-274.7 0c-12.5-12.5-32.8-12.5-45.3 0l-95.99 96c-12.5 12.5-12.5 32.8 0 45.3l96 96c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3l-73.4-73.3 73.3-73.4c12.5-12.5 12.5-32.8 0-45.3h.1z"/></svg>\n'
        }
        {...icon}
      />
      <Block className={"stat__text stat__text--language"} tag={"div"}>
        {label}
      </Block>
      <Block className={"stat__bar"} tag={"div"}>
        <Block className={"stat__fill"} tag={"div"} {...fill} />
      </Block>
      <Block className={"stat__text stat__text--pct1"} tag={"div"}>
        {value}
      </Block>
    </Block>
  );
}
