/**
 * @generated
 * @file MenuSection (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://willwong.design.webflow.com | Source site in Webflow}
 */
"use client";

import Block from "../webflow_modules/Basic/components/Block";

/**
 * Props for {@link MenuSection}
 */
export type MenuSectionProps = {
  label?: React.ReactNode;
  slot?: React.ReactNode;
};

/**
 * MenuSection
 *
 * @see {@link https://willwong.design.webflow.com | Source site in Webflow}
 */
export function MenuSection({ label = "Languages", slot }: MenuSectionProps) {
  return (
    <Block className={"menu__section"} tag={"div"}>
      <Block className={"menu__label"} tag={"div"}>
        {label}
      </Block>
      {slot}
    </Block>
  );
}
