/**
 * @generated
 * @file NavLink (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://willwong.design.webflow.com | Source site in Webflow}
 */
"use client";

import Block from "../webflow_modules/Basic/components/Block";
import HtmlEmbed from "../webflow_modules/Embed/components/HtmlEmbed";
import Link from "../webflow_modules/Basic/components/Link";

/**
 * Props for {@link NavLink}
 */
export type NavLinkProps = {};

/**
 * NavLink
 *
 * @see {@link https://willwong.design.webflow.com | Source site in Webflow}
 */
export function NavLink({}: NavLinkProps) {
  return (
    <Link
      block={"inline"}
      button={false}
      className={"nav__link"}
      options={{
        href: "#",
      }}
    >
      <HtmlEmbed
        className={"nav__icon nav__icon--open"}
        content={
          '<svg width="100%" height="100%" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2016 2016"><path d="M1369.46,974.53L791.44,391.78c-18.51-18.51-48.43-18.51-66.94,0l-77.96,77.96c-18.51,18.51-18.51,48.43,0,66.94l466.59,471.32-466.59,471.32c-18.51,18.51-18.51,48.43,0,66.94l77.96,77.96c18.51,18.51,48.43,18.51,66.94,0l578.03-582.75c18.51-18.51,18.51-48.43,0-66.94Z"/></svg>'
        }
      />
      <Block className={"nav__text"} tag={"div"}>
        {"folder_name"}
      </Block>
    </Link>
  );
}
