/**
 * @generated
 * @file Stat (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://willwong.design.webflow.com | Source site in Webflow}
 */
"use client";

import Block from "../webflow_modules/Basic/components/Block";

/**
 * Props for {@link Stat}
 */
export type StatProps = {
  label?: React.ReactNode;
  value?: React.ReactNode;
};

/**
 * Stat
 *
 * @see {@link https://willwong.design.webflow.com | Source site in Webflow}
 */
export function Stat({ label = "Age", value = "1.2 yrs" }: StatProps) {
  return (
    <Block className={"stat"} tag={"div"}>
      <Block className={"stat__text"} tag={"div"}>
        {label}
      </Block>
      <Block className={"flex-expand"} tag={"div"} />
      <Block className={"stat__text"} tag={"div"}>
        {value}
      </Block>
    </Block>
  );
}
